on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create test file
        run: uuidgen > test.artifact

      - name: PUT
        run: sh action.sh
        env:
          METHOD: PUT
          ARTIFACT: test.artifact
          TAG: test
          REGISTRY_USER: rssnyder
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move test file
        run: mv test.artifact test.artifact.old
      
      - name: Sleep
        run: sleep 10
      
      - name: GET
        run: sh action.sh
        env:
          METHOD: GET
          ARTIFACT: test.artifact
          TAG: test
          REGISTRY_USER: rssnyder
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Compare values
        run: cmp -s test.artifact.old test.artifact
